name: Blog Localization

on:
  # allows to manually run the job at any time
  workflow_dispatch:

  # # run on every push on the release branch
  # push:
  #   branches: [production, staging, master, refactor/**]

permissions:
  contents: write
  pull-requests: write

# Add concurrency group to queue builds
concurrency:
  group: blog-sync
  cancel-in-progress: false  # Queue instead of canceling

jobs:
  sync-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
      - run: yarn install
        working-directory: ./generation
      - name: "Run sync command"
        working-directory: ./generation
        env:
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        run: yarn gen:all
      - name: "Commit sync contents"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[GitHub Action] Sync blog contents from AFFiNE Cloud"
          file_pattern: "content/blog/*.json content/templates/*.json content/changelogs/*.json public/rss.xml public/sitemap.xml"
